#!/bin/sh
set -eu

: "${PORT:=10000}"
: "${WEB_ORIGIN:?WEB_ORIGIN must be configured.}"
: "${IDENTITY_EXTERNAL_HOSTNAME:?IDENTITY_EXTERNAL_HOSTNAME must be configured.}"
: "${SOCIAL_EXTERNAL_HOSTNAME:?SOCIAL_EXTERNAL_HOSTNAME must be configured.}"
: "${LEDGER_EXTERNAL_HOSTNAME:?LEDGER_EXTERNAL_HOSTNAME must be configured.}"

export PORT WEB_ORIGIN IDENTITY_EXTERNAL_HOSTNAME SOCIAL_EXTERNAL_HOSTNAME LEDGER_EXTERNAL_HOSTNAME
export KONG_PROXY_LISTEN="0.0.0.0:${PORT}"
export KONG_DECLARATIVE_CONFIG="/tmp/kong.staging.yml"

envsubst '${WEB_ORIGIN} ${IDENTITY_EXTERNAL_HOSTNAME} ${SOCIAL_EXTERNAL_HOSTNAME} ${LEDGER_EXTERNAL_HOSTNAME}' \
  < /opt/kong/kong.template.yml \
  > "${KONG_DECLARATIVE_CONFIG}"

exec /docker-entrypoint.sh kong docker-start
